# Generated by Django 3.1.7 on 2021-12-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summery', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
