# Generated by Django 3.1.7 on 2021-12-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20211209_1101'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='persons',
        ),
    ]
