# Generated by Django 3.1.7 on 2021-12-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20211209_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='github_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='youtube_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
